using System.ComponentModel;
using System.Globalization;
using Discord;
using Discord.WebSocket;
using Google.Protobuf;
using GPConf.DiscordBot.Commands;
using GPConf.DiscordBot.Services;
using GPConf.Utilities;
using ModelContextProtocol.Server;

namespace GPConf.DiscordBot.Tools;

/// <summary>
/// The bot's MCP tool surface, hosted over HTTP (see Program.cs) so race-week automation skills
/// (Claude Code / OpenCode) can make the live bot post to Discord — the one capability nothing
/// else in this codebase provides (GPConf.McpServer's stdio transport can't reach an
/// already-running process, and no Discord webhook exists). Every embed builder here is reused
/// directly from ReadCommands/PickCommands/AnalysisCommands, never reimplemented.
/// </summary>
[McpServerToolType]
public class BotMcpTools(DiscordSocketClient client, DataService data, OllamaClient ollama)
{
    private const string DefaultChannelId = "1483173357393281157"; // #race-week, guild 151923917966016514

    // Every "AI-written" step across every skill funnels through generate_and_post exactly once
    // per new piece of narrative content — a downstream step that needs to *display* content
    // already generated (by this or an earlier generate_and_post call) should format it itself
    // and use post_message instead, never feed it back through generate_and_post for a second pass.
    private const string BaseSystemPrompt =
        "You write content for a small friend-group Formula 1 confidence-cup fantasy league's " +
        "Discord server. Your tone is warm, energetic, and lightly, affectionately funny — never " +
        "corporate, never a press release.\n\n" +
        "Only use the facts given to you below. Never invent a name, number, position, or event " +
        "that isn't listed. If something interesting isn't in the facts, leave it out rather than " +
        "guessing. Numbers you're given are already final — do not recompute, double-check, or " +
        "contradict them. Do not invent quotes from drivers or players. When asked to speculate, " +
        "frame it explicitly as speculation, not as stated fact.\n\n" +
        "Structure your response into the exact sections named in the request, each starting on " +
        "its own line written exactly as '## <Section Name>'. Favor structured, scannable " +
        "formatting over walls of text: mix short prose with lists and fact bullets. Within a " +
        "section, prefer a handful of short bullet points starting with '- ' (each a single " +
        "fact or observation), and use short prose only to tie them together or set up a point. " +
        "Use **bold** around driver/player names and key numbers to make them stand out. Do not " +
        "use markdown tables, headers other than the '## ' section markers, or code fences. " +
        "Keep sections short and visually distinct — a reader should be able to scan the " +
        "bullets and get the gist without reading every word.";

    [McpServerTool]
    [Description("Posts a plain Discord embed. Use this for content the caller has already composed itself — " +
                 "e.g. a blurb already generated by generate_and_post, or prose the caller wrote directly. " +
                 "This tool never calls an LLM; it just displays what you give it.")]
    public async Task<string> PostMessage(
        [Description("Discord channel ID to post to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Embed title")] string title,
        [Description("Embed body — supports Discord markdown (bold, bullet points, etc.)")] string description,
        [Description("Optional accent color as a hex string, e.g. '1E90FF'")] string? colorHex = null,
        [Description("If true, DM dmUserId instead of posting to the channel — the closest equivalent to an " +
                     "ephemeral message for a proactively-sent post (true Discord ephemeral only exists for " +
                     "interaction responses). Race-week automation skills are announcements/calls-to-action, " +
                     "so they should leave this false.")] bool ephemeral = false,
        [Description("Discord user ID to DM when ephemeral is true")] string? dmUserId = null)
    {
        var embed = new EmbedBuilder().WithTitle(title).WithDescription(description).WithColor(ParseColor(colorHex)).Build();
        return await SendAsync(channelId, ephemeral, dmUserId, embed);
    }

    [McpServerTool]
    [Description("Posts the confidence-cup scoring rules for a race plus its pick deadline, as a Discord embed. " +
                 "Reuses the exact embed /pick-submit shows players.")]
    public async Task<string> PostPickDeadlineReminder(
        [Description("Discord channel ID to post to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Season name or year")] string season,
        [Description("Race name or round")] string race,
        [Description("Unix epoch seconds the picks deadline falls at")] long deadlineEpoch,
        [Description("League name (optional, disambiguates if needed)")] string? league = null,
        [Description("If true, DM dmUserId instead of posting to the channel.")] bool ephemeral = false,
        [Description("Discord user ID to DM when ephemeral is true")] string? dmUserId = null)
    {
        var mainData = data.Load();
        var s = data.FindSeason(mainData, season);
        if (s is null) return $"Season '{season}' not found.";
        var target = data.FindRace(s, race);
        if (target is null) return $"Race '{race}' not found in {s.Name}.";
        var (_, gs) = data.FindGameSeason(mainData, s, league);
        if (gs is null) return $"No game season found for '{s.Name}'.";

        var rules = gs.PickRules ?? new PickRules();
        var prevRace = s.Races.OrderBy(x => x.Round).LastOrDefault(x => x.Round < target.Round);
        var noPriorRace = prevRace is null;
        var eligiblePairs = CCUtils.GetEligibleDriversWithPos(s, prevRace, rules.PositionCutoff);
        var (_, legend) = PickCommands.BuildTierInfo(rules, noPriorRace, eligiblePairs);

        var built = PickCommands.BuildScoringRulesEmbed(target, rules, noPriorRace, legend);
        var deadlineLine = $"\n**Picks close:** <t:{deadlineEpoch}:F> (<t:{deadlineEpoch}:R>)";
        var embed = new EmbedBuilder()
            .WithTitle(built.Title)
            .WithDescription(built.Description + deadlineLine)
            .WithColor(built.Color ?? Color.Blue)
            .Build();
        return await SendAsync(channelId, ephemeral, dmUserId, embed);
    }

    [McpServerTool]
    [Description("Posts the same public 'Make Your Picks' announcement embed+button /pick-announce posts, " +
                 "for the next upcoming (not-yet-decided) race. Each click opens a fresh, private picker for " +
                 "whoever clicked it.")]
    public async Task<string> PostPickAnnouncement(
        [Description("Discord channel ID to post to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Season name or year")] string season,
        [Description("League name (optional; if omitted, each clicker's league is auto-detected)")] string? league = null,
        [Description("If true, prefixes the message with an @here mention as a call-to-action.")] bool mentionHere = false,
        [Description("Unix epoch seconds the picks deadline falls at. Recorded on the race so picks are rejected and the button is stripped at that time.")] long? deadlineEpoch = null,
        [Description("If true, DM dmUserId instead of posting to the channel.")] bool ephemeral = false,
        [Description("Discord user ID to DM when ephemeral is true")] string? dmUserId = null)
    {
        var mainData = data.Load();
        var s = data.FindSeason(mainData, season);
        if (s is null) return $"Season '{season}' not found.";
        var target = data.NextPickableRace(s);
        if (target is null) return $"No upcoming race to pick for in {s.Name} — every race already has results.";

        ByteString? leagueId = null;
        if (league is not null)
        {
            var (l, gs) = data.FindGameSeason(mainData, s, league);
            if (l is null || gs is null) return $"League '{league}' not found for {s.Name}.";
            leagueId = l.Id;
        }

        var (embed, button) = PickCommands.BuildPickAnnouncement(s, target, leagueId);
        var sent = await SendAsyncCore(channelId, ephemeral, dmUserId, embed, button, mentionHere: mentionHere);
        if (sent is null) return ephemeral
            ? $"ephemeral is true but dmUserId is missing or not a valid Discord user ID."
            : "Couldn't resolve the target channel.";

        // Record the deadline and the announcement's message ID on the race so pick-lockin can
        // strip the button at the deadline (and so a late pick/button-click is rejected).
        if (deadlineEpoch is { } deadline)
        {
            data.RecordPickDeadlineAndAnnouncement(s.Id, target.Id, deadline, sent.Id.ToString());
            return ephemeral ? $"DMed {dmUserId}." : $"Posted to channel {sent.Channel.Id} (deadline {deadlineEpoch} recorded).";
        }

        return ephemeral ? $"DMed {dmUserId}." : $"Posted to channel {sent.Channel.Id}.";
    }

    [McpServerTool]
    [Description("Strips the 'Make Your Picks' button from a race's pick-announcement message (the one " +
                 "post_pick_announcement recorded), replacing it with a 'picks closed' note. Meant to be called " +
                 "by pick-lockin right after the deadline passes. Uses the announcement message ID stored on the race; " +
                 "no-op if none is recorded or the message is already gone.")]
    public async Task<string> ClosePickAnnouncement(
        [Description("Discord channel ID the announcement was posted to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Season name or year")] string season,
        [Description("Race name or round")] string race)
    {
        var mainData = data.Load();
        var s = data.FindSeason(mainData, season);
        if (s is null) return $"Season '{season}' not found.";
        var r = data.FindRace(s, race);
        if (r is null) return $"Race '{race}' not found in {s.Name}.";

        var idStr = r.AnnouncementMessageId;
        if (string.IsNullOrEmpty(idStr) || !ulong.TryParse(idStr, out var msgId))
            return $"No pick-announcement message recorded for {r.Name} — nothing to close.";

        // Resolve the channel (same fallback chain as SendAsyncCore).
        var targetChannel = channelId ?? Environment.GetEnvironmentVariable("CONF_DISCORD_CHANNEL_ID") ?? DefaultChannelId;
        if (!ulong.TryParse(targetChannel, out var channelUlong))
            return $"'{targetChannel}' isn't a valid Discord channel ID.";
        var channel = await client.Rest.GetChannelAsync(channelUlong) as IMessageChannel;
        if (channel is null) return $"Couldn't resolve channel {channelUlong}.";

        try
        {
            var msg = await channel.GetMessageAsync(msgId) as IUserMessage;
            if (msg is null) return $"Couldn't resolve announcement message {msgId}.";
            await msg.ModifyAsync(m => m.Components = new ComponentBuilder().Build());
        }
        catch (Discord.Net.HttpException)
        {
            return $"Couldn't edit announcement message {msgId} (already gone?).";
        }
        catch (Exception ex)
        {
            return $"Couldn't close announcement: {ex.Message}";
        }

        // Clear the stored message ID so a re-run of pick-lockin doesn't try to re-edit a stale one.
        data.ClearAnnouncementMessageId(s.Id, r.Id);
        return $"Closed pick-announcement for {r.Name} (button stripped from message {msgId}).";
    }

    [McpServerTool]
    [Description("Posts every participating player's picks for a race, ranked by highest potential score, " +
                 "unconditionally (no pre-race secrecy gate — unlike /pick, which keeps other players' picks " +
                 "secret until the race has results). Intended for the one moment that calls for an " +
                 "unconditional reveal: right after the pick deadline passes.")]
    public async Task<string> PostPickReveal(
        [Description("Discord channel ID to post to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Season name or year")] string season,
        [Description("Race name or round")] string race,
        [Description("League name (optional)")] string? league = null,
        [Description("If true, DM dmUserId instead of posting to the channel.")] bool ephemeral = false,
        [Description("Discord user ID to DM when ephemeral is true")] string? dmUserId = null)
    {
        var mainData = data.Load();
        var s = data.FindSeason(mainData, season);
        if (s is null) return $"Season '{season}' not found.";
        var r = data.FindRace(s, race);
        if (r is null) return $"Race '{race}' not found in {s.Name}.";
        var (_, gs) = data.FindGameSeason(mainData, s, league);
        if (gs is null) return $"No game season found for '{s.Name}'.";
        var gameRace = gs.Races.FirstOrDefault(gr => gr.RaceId == r.Id);
        if (gameRace is null) return $"No picks recorded for '{r.Name}'.";

        var embed = ReadCommands.BuildPickEmbed(data, s, gs, r, gameRace, gs.ParticipatingPlayers);
        return await SendAsync(channelId, ephemeral, dmUserId, embed);
    }

    [McpServerTool]
    [Description("Posts race results for a race, with confidence-cup pick attribution when a league is resolved. " +
                 "Reuses the exact embed /results shows.")]
    public async Task<string> PostRaceResults(
        [Description("Discord channel ID to post to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Season name or year")] string season,
        [Description("Race name or round")] string race,
        [Description("League name (optional, enables confidence-cup pick attribution)")] string? league = null,
        [Description("If true, DM dmUserId instead of posting to the channel.")] bool ephemeral = false,
        [Description("Discord user ID to DM when ephemeral is true")] string? dmUserId = null)
    {
        var mainData = data.Load();
        var s = data.FindSeason(mainData, season);
        if (s is null) return $"Season '{season}' not found.";
        var r = data.FindRace(s, race);
        if (r is null) return $"Race '{race}' not found in {s.Name}.";
        if (r.RaceResults.Count == 0) return $"No race results stored for '{r.Name}'.";

        var (_, gs) = data.FindGameSeason(mainData, s, league);
        var embed = ReadCommands.BuildResultsEmbed(data, s, r, gs);
        return await SendAsync(channelId, ephemeral, dmUserId, embed);
    }

    [McpServerTool]
    [Description("Posts championship standings (driver points) or confidence-cup standings (player scores) for a season. " +
                 "Reuses the exact embeds /standings and /scores show.")]
    public async Task<string> PostStandings(
        [Description("Discord channel ID to post to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Season name or year")] string season,
        [Description("Race name or round to compute standings through (defaults to latest)")] string? race = null,
        [Description("League name (optional; required for confidenceCup)")] string? league = null,
        [Description("If true, posts confidence-cup player standings instead of the driver championship")] bool confidenceCup = false,
        [Description("If true, DM dmUserId instead of posting to the channel.")] bool ephemeral = false,
        [Description("Discord user ID to DM when ephemeral is true")] string? dmUserId = null)
    {
        var mainData = data.Load();
        var s = data.FindSeason(mainData, season);
        if (s is null) return $"Season '{season}' not found.";
        var target = race is null ? data.LatestRace(s) : data.FindRace(s, race);
        if (target is null) return $"Race '{race}' not found in {s.Name}.";

        Embed embed;
        if (confidenceCup)
        {
            var (_, gs) = data.FindGameSeason(mainData, s, league);
            if (gs is null) return $"No game season found for '{s.Name}'.";
            embed = ReadCommands.BuildScoresEmbed(data, s, gs, target);
        }
        else
        {
            embed = ReadCommands.BuildStandingsEmbed(data, mainData, s, target, league);
        }
        return await SendAsync(channelId, ephemeral, dmUserId, embed);
    }

    [McpServerTool]
    [Description("Generates narrative content via the local Ollama model from facts the caller has already " +
                 "researched, and posts it as a Discord embed with one field per section. The model only " +
                 "narrates factsMarkdown — it never invents facts, same anti-hallucination contract as the " +
                 "/driver-analysis-style slash commands. Call this once per genuinely new piece of narrative " +
                 "content. If a later step needs to display content that's already been generated (by this " +
                 "tool or by the caller itself), do NOT call this again — format it as markdown and use " +
                 "post_message instead.")]
    public async Task<string> GenerateAndPost(
        [Description("Discord channel ID to post to. Falls back to CONF_DISCORD_CHANNEL_ID if omitted.")] string? channelId,
        [Description("Embed title")] string title,
        [Description("Real facts already researched by the caller — the model narrates only these, never " +
                     "inventing names/numbers/events not listed here.")] string factsMarkdown,
        [Description("Comma-separated section labels the model must use, in order, e.g. " +
                     "'Track & History, Storylines Since Last Race, What To Watch'. Include your own emoji in " +
                     "a label if you want one, e.g. '🏎️ Track & History'.")] string sections,
        [Description("Extra tone/style guidance appended to the base system prompt, e.g. 'race-weekend " +
                     "preview, speculative and upbeat about who could succeed or struggle' or 'grounded " +
                     "post-race recap, backed only by the facts given'.")] string? styleGuidance = null,
        [Description("Optional accent color as a hex string, e.g. '1E90FF'")] string? colorHex = null,
        [Description("If true, DM dmUserId instead of posting to the channel.")] bool ephemeral = false,
        [Description("Discord user ID to DM when ephemeral is true")] string? dmUserId = null)
    {
        var sectionLabels = sections.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (sectionLabels.Length == 0) return "sections must list at least one section label.";

        var systemPrompt = BaseSystemPrompt + (string.IsNullOrWhiteSpace(styleGuidance) ? "" : $"\n\nStyle guidance: {styleGuidance}");
        var userPrompt = $"{factsMarkdown}\n\nStructure your response into these sections, in this order: {string.Join(", ", sectionLabels)}.";

        string text;
        try { text = await ollama.GenerateAsync(systemPrompt, userPrompt); }
        catch (OllamaException ex) { return $"Couldn't generate content: {ex.Message}"; }

        var builder = new EmbedBuilder().WithTitle(title).WithColor(ParseColor(colorHex));
        var parsed = AnalysisCommands.ParseSections(text);
        if (parsed.Count > 0)
        {
            foreach (var label in sectionLabels)
            {
                if (!parsed.TryGetValue(label, out var body) || body.Length == 0) continue;
                if (body.Length > AnalysisCommands.MaxFieldLength) body = body[..AnalysisCommands.MaxFieldLength] + "…";
                builder.AddField(label, body);
            }
        }
        else
        {
            // Model ignored the section format — fall back to a plain description so nothing breaks.
            builder.WithDescription(text.Length > AnalysisCommands.MaxDescriptionLength ? text[..AnalysisCommands.MaxDescriptionLength] + "…" : text);
        }

        return await SendAsync(channelId, ephemeral, dmUserId, builder.Build());
    }

    // Resolves either a channel (normal path) or a DM channel to dmUserId (ephemeral path) via
    // REST, not the gateway cache — the bot runs with GatewayIntents.None (it only ever handles
    // slash-command interactions, which carry their own channel/guild context), so the socket
    // cache never gets populated with guild/channel data. REST lookups work regardless.
    private async Task<string> SendAsync(string? channelId, bool ephemeral, string? dmUserId, Embed embed,
        MessageComponent? components = null, bool mentionHere = false)
    {
        var sent = await SendAsyncCore(channelId, ephemeral, dmUserId, embed, components, mentionHere);
        if (sent is null) return $"Couldn't resolve the target channel/user for {channelId ?? dmUserId}.";
        return ephemeral ? $"DMed {dmUserId}." : $"Posted to channel {sent.Channel.Id}.";
    }

    // Like SendAsync but returns the sent message (null on resolution failure) so callers that
    // need to later edit/delete it can capture its ID.
    private async Task<IUserMessage?> SendAsyncCore(string? channelId, bool ephemeral, string? dmUserId, Embed embed,
        MessageComponent? components = null, bool mentionHere = false)
    {
        IMessageChannel? channel;
        if (ephemeral)
        {
            if (dmUserId is null || !ulong.TryParse(dmUserId, out var uid))
                return null;
            var user = await client.Rest.GetUserAsync(uid);
            if (user is null) return null;
            channel = await user.CreateDMChannelAsync();
        }
        else
        {
            // Default target for every race-week automation skill: #race-week (guild 151923917966016514).
            // CONF_DISCORD_CHANNEL_ID overrides this; an explicit channelId argument overrides both.
            var idStr = channelId ?? Environment.GetEnvironmentVariable("CONF_DISCORD_CHANNEL_ID") ?? DefaultChannelId;
            if (!ulong.TryParse(idStr, out var id))
                return null;
            channel = await client.Rest.GetChannelAsync(id) as IMessageChannel;
            if (channel is null) return null;
        }

        var allowedMentions = mentionHere ? new AllowedMentions(AllowedMentionTypes.Everyone) : null;
        return await channel.SendMessageAsync(mentionHere ? "@here" : null, embed: embed, components: components, allowedMentions: allowedMentions);
    }

    private static Color ParseColor(string? hex)
    {
        if (string.IsNullOrWhiteSpace(hex)) return Color.Blue;
        var cleaned = hex.TrimStart('#');
        return uint.TryParse(cleaned, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var packed)
            ? new Color((byte)((packed >> 16) & 0xFF), (byte)((packed >> 8) & 0xFF), (byte)(packed & 0xFF))
            : Color.Blue;
    }
}
